To fix the automated tests in test_search.py
FAILED tests/test_search.py::test_regression_search_in_area - sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) no spatial operator found for 'st_dwithin': opfamil...
ERROR tests/test_search.py::test_UserSearch - sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) no spatial operator found for 'st_contains': opfami...

The failure did not happen when tests were run individually, suggesting
it was due to test interaction.